### ISSUE TITLE
Replace_polymorphic_compare in Base but not Core

### ISSUE THREAD

**Issue by bcc32** [janestreet/core#105]
One of the main mentions in the [new Base documentation](https://ocaml.janestreet.com/ocaml-core/latest/doc/base/) is that the default comparison operators exposed by Base are the integer ones rather than the polymorphic ones.  Core_kernel and Core, being extensions of Base, I would expect to behave the same (and IIRC they did in the past?).  However, they do not:

```
─( 23:49:30 )─< command 0 >──────────────────────────────────────{ counter: 0 }─
utop # #show (<);;
external ( < ) : 'a -> 'a -> bool = "%lessthan"
─( 23:49:32 )─< command 1 >──────────────────────────────────────{ counter: 0 }─
utop # #show Base.(<);;
val ( < ) : int -> int -> bool
─( 23:49:34 )─< command 2 >──────────────────────────────────────{ counter: 0 }─
utop # #show Core.(<);;
external ( < ) : 'a -> 'a -> bool = "%lessthan"
```

(Core_kernel gives the same result as Core).

[Is this intentional, or is this just a bug?](https://www.youtube.com/watch?v=fJ9rUzIMcZQ)

**Comment by yminsky** [comment]
This is intentional, though we've contemplated switching Core. It would be a huge and churn-y change. Instead, you can recover the Base behavior by opening Int.Replace_polymorphic_compare, which we do increasingly often in our production code.

It's worth noting that module implicits, if/when it lands, will perhaps offer a less churny-y, and yet principled, way out of this.
