### ISSUE TITLE
`Core.Map` doesn't expose `Or_duplicate.t`

### ISSUE THREAD

**Issue by arbipher** [janestreet/core#170]
The consequence is when I need to annotate the type for a function getting the result of `Core.Map.add` ([doc](https://v3.ocaml.org/p/core/latest/doc/Core/Map/index.html#val-add), [src](https://github.com/janestreet/core/blob/eb68f00fea28c20d9aab4314b0af1e0116f59f53/core/src/map.mli#L312)), I have to use `int Core.Map_intf.Or_duplicate.t`.

`Base.Map` exposes `Or_duplicate.t`. `int Base.Map.Or_duplicate.t` works fine.

**Comment by ceastlund** [comment]
It's definitely awkward that `Base` and `Core` export things differently. But it's a big lift to move the whole interface around to make them more similar, since we'd have to update a lot of code that refers to things as they are. So we're not likely to change it imminently.

For now, referring to this via `Map_intf` is the right way.
