### ISSUE TITLE
ocamldoc doesn't appear in ocp-browser when I hit the space bar

### ISSUE THREAD

**Issue by UnixJunkie** [janestreet/core#82]

**Comment by shepard8** [comment]
You have to use the package in which the function is documented.

For example, looking at `Core.List.mem` in ocp-browser will show no documentation, while `Base.List.mem` will show `Checks whether the provided element is there, using [equal].`

This is also true on the online API documentation ([Core.List.mem](https://ocaml.janestreet.com/ocaml-core/v0.9/doc/core_kernel/Core_kernel__/Std_internal/List/index.html#val-mem) [Base.List.mem](https://ocaml.janestreet.com/ocaml-core/v0.9/doc/base/Base__List/index.html#val-mem)). Finding the documentation for Core.List.mem starting from [there](https://ocaml.janestreet.com/ocaml-core/v0.9/doc/core/index.html) is not _that_ easy. I think exporting the documentation from Base to Core_kernel (and maybe from Core_kernel to Core) would help Core newcomers.

**Comment by lpw25** [comment]
This isn't likely to be fixed in the near future. `Core.List` re-exposes `Base.List` using `module type of struct include Base.List` which results in dropping the documentation.

The compiler will probably be improved soon (hopefully 4.06) to allow it to use `module type of Base.List` instead which would then be documented correctly by [odoc](http://github.com/ocaml-doc/odoc). Another possibility is that odoc might added explicit support to recognise this pattern -- but since that pattern shouldn't be needed soon I'm unlikely to do that.

As for ocp-browser, I have no idea how it works so I can't say whether it will be fixed by the change to `module type of Base.List` or if it is likely to add explicit support for `module type of struct include ... end`. I suspect that it is just grabbing the documentation directly from the `.cmt` file, which is the easiest way to get implement something that mostly works but tends to fall down on corner cases like this one.
