### ISSUE TITLE
Why core do'not support windows?

### ISSUE THREAD

**Issue by damon-kwok** [janestreet/core#84]
Why core do'not support windows?

**Comment by yminsky** [comment]
Core depends on various UNIX-isms. Core_kernel is the portable part of
Core, which should work fine on Windows.

y

**Comment by damon-kwok** [comment]
thanks

**Comment by superherointj** [comment]
This lack of windows support is quite limiting and very unfortunate since Jane's Core is "core" to Occam (at least in the books/examples I found). Even a Hello world example at Exercism uses it.
It makes a lot harder for newcomers (from Windows) to try the language and get something going. Lots of people don't use Linux/Mac. Being a newbie myself trying to learn Ocaml, and having a Windows desktop, I can testify to it. I have been struggling with tooling and trying to get things going. While Ocaml the language is straight forward the tooling in my experience in Windows hasn't been so. I'm not sure if I followed a bad guide or my understanding is lacking (in that case if you could enlight me I'd appreciate.

Sadly I cannot help fix this. I have no experience. So, I'm sorry for not offering any solution. But still I wanted to output my thoughts and frustration on topic. And I wish / hope it gets improved somehow.

**Comment by seliopou** [comment]
Closing, as this seems to be resolved.
