### ISSUE TITLE
Cannot load required shared library dllcore_kernel_stubs in macOS 10.11.6

### ISSUE THREAD

**Issue by liweijian** [janestreet/core#87]
I've `rm -rf ~/.opam` and `opam init` again, but the error still exists.

```
utop # #require "core.top";;
Cannot load required shared library dllcore_kernel_stubs.
Reason: /Users/liweijian/.opam/4.04.1/lib/stublibs/dllcore_kernel_stubs.so: dlopen(/Users/liweijian/.opam/4.04.1/lib/stublibs/dllcore_kernel_stubs.so, 138): Symbol not found: _clock_gettime
  Referenced from: /Users/liweijian/.opam/4.04.1/lib/stublibs/dllcore_kernel_stubs.so
  Expected in: flat namespace
 in /Users/liweijian/.opam/4.04.1/lib/stublibs/dllcore_kernel_stubs.so.
Cannot load required shared library dllcore_stubs.
Reason: /Users/liweijian/.opam/4.04.1/lib/stublibs/dllcore_stubs.so: dlopen(/Users/liweijian/.opam/4.04.1/lib/stublibs/dllcore_stubs.so, 138): Symbol not found: _core_kernel_time_ns_format_tm
  Referenced from: /Users/liweijian/.opam/4.04.1/lib/stublibs/dllcore_stubs.so
  Expected in: flat namespace
 in /Users/liweijian/.opam/4.04.1/lib/stublibs/dllcore_stubs.so.
Error: Reference to undefined global `Core_kernel__Core_printf'
```

The version

```bash
$ ocaml -version
The OCaml toplevel, version 4.04.1
$ opam show --field=version utop
2.0.1
$ opam show --field=version core
v0.9.1
```

However, on my another laptop with ubuntu 16.04, it works well.

**Comment by agarwal** [comment]
Try running `xcode-select --install`.

**Comment by liweijian** [comment]
@agarwal Thanks for your reply

<img width="569" alt="screen shot 2017-06-17 at 10 51 02 am" src="https://user-images.githubusercontent.com/19320783/27249551-f8496b8a-534a-11e7-89c4-62c2413723ae.png">

**Comment by liweijian** [comment]
It seems that `libcore_stubs.a(timespec.o)` is incompatible with OSX 10.11 anymore, I tried to `corebuild` and found that

```bash
ld: warning: object file (/Users/liweijian/.opam/4.04.1/lib/core/libcore_stubs.a(timespec.o)) was built for newer OSX version (10.12) than being linked (10.11)
Undefined symbols for architecture x86_64:
  "_clock_getres", referenced from:
      _unix_clock_getres in libcore_stubs.a(unix_stubs.o)
     (maybe you meant: _unix_clock_getres)
  "_clock_gettime", referenced from:
      _unix_clock_gettime in libcore_stubs.a(unix_stubs.o)
      _core_kernel_time_ns_gettime_or_zero in libcore_kernel_stubs.a(time_ns_stubs.o)
     (maybe you meant: _unix_clock_gettime)
  "_clock_settime", referenced from:
      _unix_clock_settime in libcore_stubs.a(unix_stubs.o)
     (maybe you meant: _unix_clock_settime)
  "_mkostemp", referenced from:
      _unix_mkstemp in libcore_stubs.a(unix_stubs.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
Command exited with code 2.
```

**Comment by liweijian** [comment]
I think it's related to XCode version. I'll figure it myself.

**Comment by mars0i** [comment]
I had a similar problem.  The problem seems to result from using XCode 8 on Mac OS 10.11.  There are lots of reports around the web about the problem.  A solution is to run  `sudo xcode-select --install`, as suggested for example here: http://ics.upjs.sk/~novotnyr/blog/2160/installing-ruby-2-3-1-on-el-capitan-and-xcode-8 .   Running this command installs additional software, and may take a few minutes.  

Then I had to recompile all of my OCaml packages (or maybe only some, but a lot of them, anyway).  To do this, I ended up using `opam switch export somefilename` to export the configuration to a file.  Then I removed my 4.04.1 switch and created a new 4.04.1 switch, in which I ran `opam switch import somefilename` to reinstall all of the packages I wanted.  I'm sure there's a simpler way to recompile all of the packages.
