### ISSUE TITLE
Time equality after serialization

### ISSUE THREAD

**Issue by bradlangel** [janestreet/core#94]
```
let x = Time.now () in
let y = Time.of_string (Time.to_string x) in
(* The following assertions sometimes throw *)
assert (x = y);
assert (Time.equal x y);

let z = Time.t_of_sexp (Time.sexp_of_t x) in
(* The following assertions sometimes throw *)
assert (x = z);
assert (Time.equal x z)
```

Is this expected behavior when serializing from Time.t to {Sexp.t, string} and
back?  If there is documentation on this behavior I apologize as I wasn't able
to find it.

Core version v0.9.1
Compiler version: 4.04.2

**Comment by kevinqiu** [comment]
Hi, I've also experienced this problem, although I'm not able to provide a meaningful `x`, `y`, or `z`. By which I mean, I can print out the result of `Time.to_string`, but if I round trip the output of that, it seems fine. Is there a way to get at the underlying float? It seems like there is a problem with that(perhaps the bug you're alluding to?) In any case, here is an example where it threw.

```
let x = Time.now () in
let y = Time.of_string (Time.to_string x) in
print_endline (Time.to_string x);
print_endline (Time.to_string y);
print_endline (Float.to_string (Time.Span.to_ms (Time.to_span_since_epoch x)));
print_endline (Float.to_string (Time.Span.to_ms (Time.to_span_since_epoch y)));
assert (x = y);
assert (Time.equal x y);;
```
Time.to_string x: 2017-08-08 15:16:17.836001-04:00                                                                     
Time.to_string y: 2017-08-08 15:16:17.836001-04:00                                                                     
Time.Span.to_ms x: 1.50221977784e+12
Time.Span.to_ms y: 1.50221977784e+12
Exception: "Assert_failure //toplevel//:8:0".
Raised at file "//toplevel//", line 8, characters 0-14
Called from file "toplevel/toploop.ml", line 180, characters 17-56

But then, doing the following is ok:
```
let x = Time.of_string "2017-08-08 15:16:17.836001-04:00  " in
let y =Time.of_string (Time.to_string x) in
assert (x = y);
assert (Time.equal x y);
```

**Comment by bmillwood** [comment]
Oh, I guess there's also a roundtrip bug with `Float.to_string` :/

The good news is that I think *that* one is already fixed, and just awaiting the next release.

The further good news is that `sprintf "%.20g" ought to crudely do the trick in the interim (I didn't think too hard about 20, but it ought to be enough).

**Comment by kevinqiu** [comment]
Ah yes, that worked! Here's an example of x & y that causes the bug:

```
let x = Time.now () in
let y = Time.of_string (Time.to_string x) in
print_endline (sprintf "%.20g" (Time.Span.to_ms (Time.to_span_since_epoch x)));
print_endline (sprintf "%.20g" (Time.Span.to_ms (Time.to_span_since_epoch y)));
```
results in:
1502291708998.4873047
1502291708998.4870605

and then, just reading in the float:

```
let x = Time.of_span_since_epoch (Time.Span.of_ms 1502291708998.4873047) in
let y = Time.of_string (Time.to_string x) in
print_endline (sprintf "%.20g" (Time.Span.to_ms (Time.to_span_since_epoch x)));
print_endline (sprintf "%.20g" (Time.Span.to_ms (Time.to_span_since_epoch y)));;
```

1502291708998.4873047
1502291708998.4870605

Same values as before.

**Comment by mbarbin** [comment]
The issue with `Float.to_string` has been fixed.

`let x = Time.now () ;;
val x : Time.t = 2018-01-24 09:32:45.750498-05:00

let y = Time.of_string (Time.to_string x) ;;
val y : Time.t = 2018-01-24 09:32:45.750498-05:00

Time.equal x y ;;
- : bool = false

let s1 = Time.Span.to_ms (Time.to_span_since_epoch x) ;;
val s1 : float = 1516804365750.4976

let s2 = Time.Span.to_ms (Time.to_span_since_epoch y) ;;
val s2 : float = 1516804365750.498

String.equal (Float.to_string s1) (Float.to_string s2) ;;
- : bool = false
`

But the issue is still standing.

`String.equal (Time.to_string x) (Time.to_string y) ;;
- : bool = true

Sexp.equal (Time.sexp_of_t x) (Time.sexp_of_t y) ;;
- : bool = true
`

The issue is due to `Ofday.to_string` which is not injective.
`Ofday.to_string` limits the precision to 15 chars max (hard coded in
`Ofday.to_string`).  In both case the value is serialized with an
Ofday part of:

`09:32:45.750498`

which lacks the precision necessary to distinguish x from y.

Since `Time.to_string` uses `Ofday.to_string` to build part of the
string, it inherits this property.  Thus, `Time.to_string` and thus
`Time.sexp_of_t` are not injective.

I am not sure whether the currently adopted syntax for
`Time.to_string` follows a specification in particular.  In the code,
the name `iso8601_extended` appears at several places.  Maybe we would
not be free to extend the precision of `Ofday.to_string` without
breaking something, or existing deserializers.  To be investigated.
If the max length supported on deserialization is already reached and
limited to 15, we might have to mint a set of V2 modules for Ofday &
Time serializations to fix this.
