### ISSUE TITLE
core_time has issues with TZ=':/etc/localtime'

### ISSUE THREAD

**Issue by toolslive** [janestreet/core#96]
http://kirste.userpage.fu-berlin.de/chemnet/use/info/libc/libc_17.html#SEC301

```
 If the TZ environment variable does not have a value, the operation chooses a time zone 
by default. In the GNU C library, the default time zone is like the specification 
`TZ=:/etc/localtime'  (or `TZ=:/usr/local/etc/localtime', depending on how GNU C library 
was configured;  see section How to Install the GNU C Library). 

Other C libraries use their own rule for choosing the default time zone, so there is little 
we can say about them. 
```

Systemd advocates this practice: `DefaultEnvironment=TZ=:/etc/localtime` , but core has issues with that:
`("unknown zone" (zone :/etc/localtime))`

**Comment by yminsky** [comment]
Hmm. It's not clear I guess what the portable behavior is here. That makes everything more painful.

> :characters
> Each operating system interprets this format differently; in the GNU C library, characters is the name of a file which describes the time zone.

I suspect it's not a good idea to allow completely arbitrary file-name, since for setuid executables that use the TZ variable, you can get the executable to read an arbitrary file. That doesn't immediately suggest an exploit, but it's a step in the wrong direction.

In any case, given that systemd uses this, it sounds plausible that this should be fixed somehow in Core, even though it's a non-portable behavior.

An effective way of speeding this along would be a PR, of course...
