### ISSUE TITLE
jbuilder external-lib-deps fails on irrelevant unreadable directories

### ISSUE THREAD

**Issue by mars0i** [janestreet/core#98]
I'm getting an error installing `core` with `opam` (see message below), but this issue is about the suggested fix, to run `jbuilder external-lib-deps --missing -p core_kernel @install`.   I'm guessing that this command searches through every directory under the current directory, because it's failing on unreadable directories two levels below my home dir.   These are directories that have nothing to do with jbuilder, core, or OCaml.  (They're unreadable because I `chmod`ed them to 000 and want them that way.)

So one point is it seems like jbuilder should not fail on an unreadable directory unless it knows that it needs that directory.  The other point is this: Why is it searching through everyone one of my directories just so that I can build `core`?    I'm sure that jbuilder is just running some default procedure that's designed for running within a project directory, but it's just slightly creepy to find that it's looking through unrelated stuff for no good reason.  Shouldn't the tip describe a command that won't do that?

(As for the error below, it looks like `core` should have a dependency specified for `base`.  When I run `opam install base`, it tells me that `base` 0.9.5 is already installed.  Then I tried to install core again, and got a similar error saying that jane-street-headers were missing, so I installed that package and tried to install core again.)

Thanks-

```
#=== ERROR while compiling core_kernel.v0.9.1 =================================#
# context      2.0.0~beta4 | darwin/x86_64 | ocaml-variants.4.05.0+flambda | https://opam.ocaml.org/2.0#2017-11-05 03:04
# path         ~/.opam/4.05.0+flambda/.opam-switch/build/core_kernel.v0.9.1
# command      jbuilder build -p core_kernel -j 1
# exit-code    1
# env-file     ~/.opam/log/core_kernel-6933-703493.env
# output-file  ~/.opam/log/core_kernel-6933-703493.out
### output ###
# Error: External library "base" not found.
# -> required by "src/config/jbuild (context default)"
# Hint: try: jbuilder external-lib-deps --missing -p core_kernel @install
```

**Comment by seliopou** [comment]
I believe that the error message makes sense given the current working directory of command when it produced the error. Specifically, the command was run in the directory `~/.opam/4.05.0+flambda/.opam-switch/build/core_kernel.v0.9.1` which is where the source tarball was inflated, and where the build was actually attempted. In normal usage, the current working directory that you run jbuilder in is the current working directory of your shell, and the hint makes sense without further qualification. When jbuilder runs via OPAM, jbuilder is not running from your shell's current working directory, and the additional `path` context is necessary to make sense of the error and the hint, which is provided though it's far away from the hint.

When a user runs the `jbuilder` command, jbuilder has no choice but to assume that the current directory is a project and begin a search through the directory tree to discover jbuild files and their corresponding libraries. If your run it from your home directory, it will make that same assumption. If it can't make that assumption, then it doesn't have much hope of making forward progress.

But having said all that, perhaps there's an opportunity to improve this error message. I would suggest opening an issue in the [jbuilder issue tracker](https://github.com/janestreet/jbuilder/issues) directly. There's a group of open-source contributors over there, and having them see this issue is your best bet for either a better explanation of the situation, or getting a fix merged.

Closing the issue, but feel free to continue the discussion if it's needed.

**Comment by mars0i** [comment]
@seliopou, I think you misunderstood.  I ran the suggested `jbuilder` command from my user `$HOME` directory, and it failed because a subdirectory unrelated to `juilder` or OCaml was unreadable.

Maybe this is a jbuilder issue, too, but at present it's a problem with trying to install `core` using opam.  As it is, core is the only common package that routinely requires me to go back and install missing packages by hand rather than managing the dependencies itself (e.g. I get an error trying to install `core` because `base` isn't installed, which on the face of it seems kind of silly).  As part of core's funky opam installation process, it tells me to try a jbuilder command, which fails for a silly reason.  If core's opam routines are telling me to do something that won't work to solve a problem (that actually shouldn't occur, imo), then that's an issue with core.  Installing core shouldn't depend on permissions I've set on directories that have nothing at all to do with OCaml.  

Sorry to be so harsh, but core is an enormous resource for the OCaml community, and it's one of the first packages that many new users will install, due to RWO.  I believe that core's installation should normally be smooth.  I've always eventually succeeded in working around the problems, but it hasn't been smooth.  (I also don't like the fact that some parts of the API docs are nearly impossible to navigate, but I understand that that's being worked on.)

I don't believe this issue should have been closed.

**Comment by mars0i** [comment]
OK, so I now think it's possible that that suggested `jbuilder` command is issued by opam and not by `core`-specific routines.  In that case it's an opam issue as well as a jbuilder issue.  I stand by my other comments about opam installation process.

**Comment by seliopou** [comment]
Feel free to open another issue about the installation problems. That part sortof got lost in the discussion of jbuilder behavior.

-Spiros E.

i sent this from my Phone.
